AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ShoppingLists:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SyncGalaxy-fnShoppingLists
      Handler: shoppingListsHandler.getShoppingLists
      Runtime: nodejs6.10
      Policies: [AmazonDynamoDBReadOnlyAccess, AmazonS3ReadOnlyAccess]
      Environment:
        Variables: 
          S3_BUCKET: SyncGalaxy-ShoppingLists-bucket
          ShoppingListsTable: SyncGalaxy-ShoppingLists-tblShoppingLists
      Events:
        GetShoppingLists:
          Type: Api
          Properties:
            Path: /SyncGalaxy/ShoppingLists
            Method: get      
        GetShoppingListsByUser:
          Type: Api
          Properties:
            Path: /SyncGalaxy/ShoppingLists/{user}
            Method: get
  ShoppingListsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: SyncGalaxy-ShoppingLists-tblShoppingLists
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S   
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH   
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5       
      StreamSpecification:
        StreamViewType: KEYS_ONLY
        