AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Post:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SyncGalaxy-fnUsers
      Handler: usersHandler.registerUser
      Runtime: nodejs8.10
      Policies: [AmazonDynamoDBReadOnlyAccess, AmazonS3ReadOnlyAccess]
      Environment:
        Variables: 
          S3_BUCKET: SyncGalaxy-Users-bucket
          UsersTable: SyncGalaxy-Users-tblUsers
      Events:
        RegisterUser:
          Type: Api
          Properties:
            Path: /SyncGalaxy/Users
            Method: post                              
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: SyncGalaxy-Users-tblUsers
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S   
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH   
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5       
      StreamSpecification:
        StreamViewType: KEYS_ONLY
        