AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Users:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Users
      Handler: usersHandler.graphqlHandler
      Runtime: nodejs8.10
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /users/graphql
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /users/graphql
            Method: post
  Options:
    Type: AWS::Serverless::Function
    Properties:                     
      FunctionName: Users-Options
      Handler: usersHandler.getOptions
      Runtime: nodejs8.10
      Events:
        GetOptions:
          Type: Api
          Properties:
            Path: /users/graphql
            Method: options              
  GraphQLInspector:
    Type: AWS::Serverless::Function
    Properties:
      Handler: usersHandler.graphiqlHandler
      Runtime: nodejs8.10
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /users/graphiql
            Method: get