AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: storesHandler.get
      Runtime: nodejs6.10
      Environment:
        Variables: 
          S3_BUCKET: SyncGalaxy-bucket
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /stores/get
            Method: GET