AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetStores:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SyncGalaxy-fnStores
      Handler: storesHandler.getStores
      Runtime: nodejs6.10
      Policies: [AmazonDynamoDBReadOnlyAccess, AmazonS3ReadOnlyAccess]
      Environment:
        Variables: 
          S3_BUCKET: SyncGalaxy-Stores-bucket
          StoresTable: SyncGalaxy-Stores-tblStores
      Events:
        GetStores:
          Type: Api
          Properties:
            Path: /SyncGalaxy/Stores
            Method: get      
        GetStoresByName:
          Type: Api
          Properties:
            Path: /SyncGalaxy/Stores/{storeName}
            Method: get
  Stores:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: SyncGalaxy-Stores-tblStores
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S   
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH   
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5       
      StreamSpecification:
        StreamViewType: KEYS_ONLY
        